services:
  pgdatabase:
    image: postgres:13
    environment: 
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DATABASE=ny_taxi
    volumes:
      - "./green_data:/var/lib/postgresql/data1:rw"
    ports:
      - "5432:5432"
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"